import { useState } from "react";
import ImageUploader from "../../components/create-listing/ImageUploader";
import ListingForm from "../../components/create-listing/ListingForm";
import toast from "react-hot-toast";
import { useNavigate } from "react-router-dom";
import api from "../../services/api";

export default function CreateListing({
  refreshListings,
}) {
  const [image, setImage] = useState(null);

  const [title, setTitle] = useState("");
  const [price, setPrice] = useState("");
  const [category, setCategory] = useState("");
  const [condition, setCondition] = useState("");
  const [description, setDescription] =
    useState("");

  const [publishing, setPublishing] =
    useState(false);

  const navigate = useNavigate();


  // ==========================================
  // PUBLISH LISTING
  // ==========================================

  const handlePublish = async () => {

    // Validate required fields
    if (
      !title.trim() ||
      !price ||
      !category ||
      !condition ||
      !description.trim()
    ) {
      toast.error(
        "Please fill in all required fields."
      );
      return;
    }


    try {

      setPublishing(true);


      // ========================================
      // SEND LISTING TO BACKEND
      // ========================================

      const response = await api.post(
        "/listings",
        {
          title: title.trim(),

          price: Number(price),

          category,

          condition,

          description:
            description.trim(),

          // Image is now the permanent
          // Base64 image generated by
          // ImageUploader
          image: image || undefined,

          isDonation: false,

          // IMPORTANT:
          // We do NOT send campus here.
          // Backend gets it from req.user.campus.

          // We also do NOT rely on this value
          // for the actual listing location.
          // Backend gets residenceHall from
          // the logged-in user.
        }
      );


      console.log(
        "Created listing:",
        response.data.listing
      );


      // ========================================
      // REFRESH FROM MONGODB
      // ========================================

      if (refreshListings) {
        await refreshListings();
      }


      // ========================================
      // SUCCESS
      // ========================================

      toast.success(
        "Listing published successfully!"
      );
      setTitle("");
      setPrice("");
      setCategory("");
      setCondition("");
      setDescription("");
      setImage(null);
      navigate("/home", {
        replace: true,
      });

    } catch (error) {

      console.error(
        "Publish listing error:",
        error
      );


      toast.error(
        error.response?.data?.message ||
        "Failed to publish listing."
      );

    } finally {

      setPublishing(false);

    }
  };


  return (
    <section className="max-w-3xl mx-auto px-6 py-16">

      {/* ======================================
          HEADER
      ====================================== */}

      <h1 className="text-5xl font-black text-stone-900">
        📦 Create Listing
      </h1>

      <p className="mt-3 text-stone-500">
        Sell something another student might need.
      </p>


      {/* ======================================
          IMAGE
      ====================================== */}

      <ImageUploader
        image={image}
        setImage={setImage}
      />


      {/* ======================================
          FORM
      ====================================== */}

      <ListingForm
        title={title}
        setTitle={setTitle}

        price={price}
        setPrice={setPrice}

        category={category}
        setCategory={setCategory}

        condition={condition}
        setCondition={setCondition}

        description={description}
        setDescription={setDescription}

        handlePublish={handlePublish}

        publishing={publishing}
      />

    </section>
  );
}